**p_matrix_Tsatsomeros** algorithm is based on :

@article{title = {Principal minors, Part I: A method for computing all the principal minors of a matrix},
journal = {Linear Algebra and its Applications},
volume = {419},
number = {1},
pages = {107-124},
year = {2006},
issn = {0024-3795},
doi = {https://doi.org/10.1016/j.laa.2006.04.008},
url = {https://www.sciencedirect.com/science/article/pii/S0024379506002126},
author = {Kent Griffin and Michael J. Tsatsomeros},
keywords = {Principal submatrix, Schur complement, P-matrix, P-problem},
abstract = {An order O(2n) algorithm for computing all the principal minors of an arbitrary n×n complex matrix is motivated and presented, offering an improvement by a factor of n3 over direct computation. The algorithm uses recursive Schur complementation and submatrix extraction, storing the answer in a binary order. An implementation of the algorithm in MATLAB® is also given and practical considerations are discussed and treated accordingly.}}

(see also :
- page 21/22 http://www.math.wsu.edu/faculty/tsat/files/PmatricesLectureNotes.pdf
- page 4 http://www.math.wsu.edu/faculty/tsat/files/tl_c.pdf)

**p_matrix_Rohn** algorithm is based on :
  
@article{title = {An Algorithm for Solving the P-Matrix Problem},
journal = {Národní úložiště šedé literatury},
url = {https://invenio.nusl.cz/record/81055/files/content.csg.pdf},
author = {Jiří Rohn},
keywords = {P-matrix problem}}

motivated by : https://www.sciencedirect.com/science/article/pii/S0024379501005900

(see also :
- https://www.sciencedirect.com/science/article/pii/S0024379511001418
- https://www.researchgate.net/publication/228571326_An_Algorithm_for_Checking_Regularity_of_Interval_Matrices)

In [1]:
from general_utils import *
from pmat_rohn_v1_utils import *
from pmat_rohn_v2_utils import *
from pmat_tsatsomeros_utils import *
import numpy as np
from math import *
import random
from sklearn.datasets import make_spd_matrix

In [2]:
n = 5
A = generate_p_matrix(n)
print("The following is a P-matrix:\n", A, "\n") # P MATRIX TRUE
print(f"Spectral radius (A) = {spectral_radius(A)}, is < 1 ? {spectral_radius(A) < 1}")

output_tsatsomeros = p_matrix_Tsatsomeros(A, False)

output_rohn_v1, J, msg_rohn_v1 = p_matrix_Rohn_v1(A, False)
if output_rohn_v1 == 1:
    output_rohn_v1 = True
elif output_rohn_v1 == 0:
    output_rohn_v1 = False
else:
    output_rohn_v1 = "ERROR_output_rohn_v1"
    
output_rohn_v2, msg_rohn_v2 = p_matrix_Rohn_v2(A, False)
if output_rohn_v2 == 1:
    output_rohn_v2 = True
elif output_rohn_v2 == 0:
    output_rohn_v2 = False
else:
    output_rohn_v2 = "ERROR_output_rohn_v2"
    
if (output_tsatsomeros == output_rohn_v1) & (output_rohn_v1 == output_rohn_v2):
    print(f"Clear answer: Is A a P-Matrix ? {output_tsatsomeros}")
else:
    print(f"Unclear answer: Is A a P-Matrix ?\noutput_tsatsomeros:{output_tsatsomeros}\noutput_rohn_v1:{output_rohn_v1}\noutput_rohn_v2:{output_rohn_v1}")

The following is a P-matrix:
 [[ 0.73455933 -0.18566603 -0.00598305 -0.10719128 -0.21943939]
 [ 0.19335542  1.35998744  0.06959179  0.13348472  0.40107474]
 [-0.23501464 -0.20209503  0.85128375 -0.13173395 -0.03037803]
 [ 0.00949402 -0.29404553 -0.21124631  0.86167691 -0.20894216]
 [-0.27315328 -0.03186015 -0.05376906 -0.29363665  0.75247861]] 

Spectral radius (A) = 1.3722202219586188, is < 1 ? False
Clear answer: Is A a P-Matrix ? True


In [3]:
A = np.array([[1,2],
              [3,-1]])
print("The following is not a P-matrix:\n", A, "\n") # P MATRIX FALSE
print(f"Spectral radius (A) = {spectral_radius(A)}, is < 1 ? {spectral_radius(A) < 1}")

output_tsatsomeros = p_matrix_Tsatsomeros(A, False)

output_rohn_v1, J, msg_rohn_v1 = p_matrix_Rohn_v1(A, False)
if output_rohn_v1 == 1:
    output_rohn_v1 = True
elif output_rohn_v1 == 0:
    output_rohn_v1 = False
else:
    output_rohn_v1 = "ERROR_output_rohn_v1"
    
output_rohn_v2, msg_rohn_v2 = p_matrix_Rohn_v2(A, False)
if output_rohn_v2 == 1:
    output_rohn_v2 = True
elif output_rohn_v2 == 0:
    output_rohn_v2 = False
else:
    output_rohn_v2 = "ERROR_output_rohn_v2"
    
if (output_tsatsomeros == output_rohn_v1) & (output_rohn_v1 == output_rohn_v2):
    print(f"Clear answer: Is A a P-Matrix ? {output_tsatsomeros}")
else:
    print(f"Unclear answer: Is A a P-Matrix ?\noutput_tsatsomeros:{output_tsatsomeros}\noutput_rohn_v1:{output_rohn_v1}\noutput_rohn_v2:{output_rohn_v1}")

The following is not a P-matrix:
 [[ 1  2]
 [ 3 -1]] 

Spectral radius (A) = 2.6457513110645907, is < 1 ? False
Clear answer: Is A a P-Matrix ? False


In [4]:
A = np.array([[1,2],
              [3,1]])
print("The following is not a P-matrix:\n", A, "\n") # P MATRIX FALSE
print(f"Spectral radius (A) = {spectral_radius(A)}, is < 1 ? {spectral_radius(A) < 1}")

output_tsatsomeros = p_matrix_Tsatsomeros(A, False)

output_rohn_v1, J, msg_rohn_v1 = p_matrix_Rohn_v1(A, False)
if output_rohn_v1 == 1:
    output_rohn_v1 = True
elif output_rohn_v1 == 0:
    output_rohn_v1 = False
else:
    output_rohn_v1 = "ERROR_output_rohn_v1"
    
output_rohn_v2, msg_rohn_v2 = p_matrix_Rohn_v2(A, False)
if output_rohn_v2 == 1:
    output_rohn_v2 = True
elif output_rohn_v2 == 0:
    output_rohn_v2 = False
else:
    output_rohn_v2 = "ERROR_output_rohn_v2"
    
if (output_tsatsomeros == output_rohn_v1) & (output_rohn_v1 == output_rohn_v2):
    print(f"Clear answer: Is A a P-Matrix ? {output_tsatsomeros}")
else:
    print(f"Unclear answer: Is A a P-Matrix ?\noutput_tsatsomeros:{output_tsatsomeros}\noutput_rohn_v1:{output_rohn_v1}\noutput_rohn_v2:{output_rohn_v1}")

The following is not a P-matrix:
 [[1 2]
 [3 1]] 

Spectral radius (A) = 3.4494897427831783, is < 1 ? False
Clear answer: Is A a P-Matrix ? False


In [5]:
A = np.array([[1,2,3],
              [3,1,3],
              [2,3,1]])
print("The following is not a P-matrix:\n", A, "\n") # P MATRIX FALSE
print(f"Spectral radius (A) = {spectral_radius(A)}, is < 1 ? {spectral_radius(A) < 1}")

output_tsatsomeros = p_matrix_Tsatsomeros(A, False)

output_rohn_v1, J, msg_rohn_v1 = p_matrix_Rohn_v1(A, False)
if output_rohn_v1 == 1:
    output_rohn_v1 = True
elif output_rohn_v1 == 0:
    output_rohn_v1 = False
else:
    output_rohn_v1 = "ERROR_output_rohn_v1"
    
output_rohn_v2, msg_rohn_v2 = p_matrix_Rohn_v2(A, False)
if output_rohn_v2 == 1:
    output_rohn_v2 = True
elif output_rohn_v2 == 0:
    output_rohn_v2 = False
else:
    output_rohn_v2 = "ERROR_output_rohn_v2"
    
if (output_tsatsomeros == output_rohn_v1) & (output_rohn_v1 == output_rohn_v2):
    print(f"Clear answer: Is A a P-Matrix ? {output_tsatsomeros}")
else:
    print(f"Unclear answer: Is A a P-Matrix ?\noutput_tsatsomeros:{output_tsatsomeros}\noutput_rohn_v1:{output_rohn_v1}\noutput_rohn_v2:{output_rohn_v1}")

The following is not a P-matrix:
 [[1 2 3]
 [3 1 3]
 [2 3 1]] 

Spectral radius (A) = 6.322365034242083, is < 1 ? False
Clear answer: Is A a P-Matrix ? False


In [6]:
# http://www.math.wsu.edu/faculty/tsat/files/pcon_c.pdf ($3 \times 3$ matrix sign pattern $\iff$ p-matrix)
    
A = np.array([[1,2,5],
              [-3,5,1],
              [0,-20,10]])

print("The following is a P-matrix:\n", A, "\n") # P MATRIX TRUE (sign pattern from the paper above)
print(f"Spectral radius (A) = {spectral_radius(A)}, is < 1 ? {spectral_radius(A) < 1}")

output_tsatsomeros = p_matrix_Tsatsomeros(A, False)

output_rohn_v1, J, msg_rohn_v1 = p_matrix_Rohn_v1(A, False)
if output_rohn_v1 == 1:
    output_rohn_v1 = True
elif output_rohn_v1 == 0:
    output_rohn_v1 = False
else:
    output_rohn_v1 = "ERROR_output_rohn_v1"
    
output_rohn_v2, msg_rohn_v2 = p_matrix_Rohn_v2(A, False)
if output_rohn_v2 == 1:
    output_rohn_v2 = True
elif output_rohn_v2 == 0:
    output_rohn_v2 = False
else:
    output_rohn_v2 = "ERROR_output_rohn_v2"
    
if (output_tsatsomeros == output_rohn_v1) & (output_rohn_v1 == output_rohn_v2):
    print(f"Clear answer: Is A a P-Matrix ? {output_tsatsomeros}")
else:
    print(f"Unclear answer: Is A a P-Matrix ?\noutput_tsatsomeros:{output_tsatsomeros}\noutput_rohn_v1:{output_rohn_v1}\noutput_rohn_v2:{output_rohn_v1}")

The following is a P-matrix:
 [[  1   2   5]
 [ -3   5   1]
 [  0 -20  10]] 

Spectral radius (A) = 11.316344038853982, is < 1 ? False
Unclear answer: Is A a P-Matrix ?
output_tsatsomeros:True
output_rohn_v1:True
output_rohn_v2:True


In [20]:
n = 8
nbr_iter = 100
pb = 0
cannot_solve = 0
v1_ok_tsatso = 0
v2_ok_tsatso = 0

for _ in range(nbr_iter):
    
    normalized_matrix = np.random.normal(loc=0.0, scale=1.0, size=(n,n)).round(3) / sqrt(n)
    matrix = np.eye(n) - normalized_matrix
    
    output_tsatsomeros = p_matrix_Tsatsomeros(matrix, False)

    output_rohn_v1, J, msg_rohn_v1 = p_matrix_Rohn_v1(matrix, False)
    if output_rohn_v1 == 1:
        output_rohn_v1 = True
    elif output_rohn_v1 == 0:
        output_rohn_v1 = False

    output_rohn_v2, msg_rohn_v2 = p_matrix_Rohn_v2(matrix, False)
    if output_rohn_v2 == 1:
        output_rohn_v2 = True
    elif output_rohn_v2 == 0:
        output_rohn_v2 = False
        
    if (output_rohn_v1 == -1) | (output_rohn_v2 == -1):
        cannot_solve += 1
    elif (output_tsatsomeros == output_rohn_v1) & (output_rohn_v1 == output_rohn_v2):
        #         print(f"\n ----- Clear answer: Is A a P-Matrix ? {output_tsatsomeros}")
        pass
    elif output_tsatsomeros == output_rohn_v1:
        v1_ok_tsatso += 1
    elif output_tsatsomeros == output_rohn_v2:
        v2_ok_tsatso += 1
    else:
        pb += 1
        #         print(f"\n ----- Unclear answer: Is A a P-Matrix ?\noutput_tsatsomeros:{output_tsatsomeros}\noutput_rohn_v1:{output_rohn_v1}\noutput_rohn_v2:{output_rohn_v2}")
        #         print("\nCall tsatsomeros:\n")
        #         output_tsatsomeros = p_matrix_Tsatsomeros(matrix, True)
        #         print(output_tsatsomeros)
        #         print("\nCall rohn v1:\n")
        #         output_rohn_v1, J, msg_rohn_v1 = p_matrix_Rohn_v1(matrix, True)
        #         print(output_rohn_v1, msg_rohn_v1)
        #         print("\nCall rohn v2:\n")
        #         output_rohn_v2, msg_rohn_v2 = p_matrix_Rohn_v2(matrix, True)
        #         print(output_rohn_v2, msg_rohn_v2)
        
print("\n\n\nCHECKING DONE")
print(r"$\Gamma$ non symmetric")
print(f"matrix shape {n}x{n}, {nbr_iter} estimations")
print(f"proportion of results where algorithms do not give the same output: {pb / (nbr_iter - cannot_solve )}")
print(f"v1_ok_tsatso {v1_ok_tsatso}, v2_ok_tsatso {v2_ok_tsatso}")

In singularity_det_descent: PROBLEM -- Program run has been stopped after reaching prescribed number of iterations when looking for beta
In singularity_det_descent: PROBLEM -- Program run has been stopped after reaching prescribed number of iterations when looking for beta
In singularity_det_descent: PROBLEM -- Program run has been stopped after reaching prescribed number of iterations when looking for beta
In singularity_det_descent: PROBLEM -- Program run has been stopped after reaching prescribed number of iterations when looking for beta
In singularity_det_descent: PROBLEM -- Program run has been stopped after reaching prescribed number of iterations when looking for beta
In singularity_det_descent: PROBLEM -- Program run has been stopped after reaching prescribed number of iterations when looking for beta
In singularity_det_descent: PROBLEM -- Program run has been stopped after reaching prescribed number of iterations when looking for beta
In singularity_det_descent: PROBLEM -- Pr

In [12]:
n = 8
nbr_iter = 100
pb = 0
cannot_solve = 0

for _ in range(nbr_iter):
    
    normalized_wigner = get_wigner((n,n)) / sqrt(n)
    matrix = np.eye(n) - normalized_wigner
    
    output_tsatsomeros = p_matrix_Tsatsomeros(matrix, False)

    output_rohn_v1, J, msg_rohn_v1 = p_matrix_Rohn_v1(matrix, False)
    if output_rohn_v1 == 1:
        output_rohn_v1 = True
    elif output_rohn_v1 == 0:
        output_rohn_v1 = False

    output_rohn_v2, msg_rohn_v2 = p_matrix_Rohn_v2(matrix, False)
    if output_rohn_v2 == 1:
        output_rohn_v2 = True
    elif output_rohn_v2 == 0:
        output_rohn_v2 = False

    if (output_rohn_v1 == -1) | (output_rohn_v2 == -1):
        cannot_solve += 1
    if (output_tsatsomeros == output_rohn_v1) & (output_rohn_v1 == output_rohn_v2):
        #         print(f"\n ----- Clear answer: Is A a P-Matrix ? {output_tsatsomeros}")
        pass
    else:
        pb += 1
        #         print(f"\n ----- Unclear answer: Is A a P-Matrix ?\noutput_tsatsomeros:{output_tsatsomeros}\noutput_rohn_v1:{output_rohn_v1}\noutput_rohn_v2:{output_rohn_v2}")
        #         print("\nCall tsatsomeros:\n")
        #         output_tsatsomeros = p_matrix_Tsatsomeros(matrix, True)
        #         print(output_tsatsomeros)
        #         print("\nCall rohn v1:\n")
        #         output_rohn_v1, J, msg_rohn_v1 = p_matrix_Rohn_v1(matrix, True)
        #         print(output_rohn_v1, msg_rohn_v1)
        #         print("\nCall rohn v2:\n")
        #         output_rohn_v2, msg_rohn_v2 = p_matrix_Rohn_v2(matrix, True)
        #         print(output_rohn_v2, msg_rohn_v2)
        
print("\n\n\nCHECKING DONE")
print(r"$W$ symmetric")
print(f"matrix shape {n}x{n}, {nbr_iter} estimations")
print(f"proportion of results where algorithms do not give the same output: {pb / (nbr_iter - cannot_solve )}")




CHECKING DONE
$W$ symmetric
matrix shape 8x8, 100 estimations
proportion of results where algorithms do not give the same output: 0.05


In [14]:
n = 8
nbr_iter = 100
pb = 0
cannot_solve = 0

for _ in range(nbr_iter):
    
    matrix = make_spd_matrix(n).round(3)
    
    output_tsatsomeros = p_matrix_Tsatsomeros(matrix, False)

    output_rohn_v1, J, msg_rohn_v1 = p_matrix_Rohn_v1(matrix, False)
    if output_rohn_v1 == 1:
        output_rohn_v1 = True
    elif output_rohn_v1 == 0:
        output_rohn_v1 = False

    output_rohn_v2, msg_rohn_v2 = p_matrix_Rohn_v2(matrix, False)
    if output_rohn_v2 == 1:
        output_rohn_v2 = True
    elif output_rohn_v2 == 0:
        output_rohn_v2 = False

    if (output_rohn_v1 == -1) | (output_rohn_v2 == -1):
        cannot_solve += 1
    if (output_tsatsomeros == output_rohn_v1) & (output_rohn_v1 == output_rohn_v2):
        #         print(f"\n ----- Clear answer: Is A a P-Matrix ? {output_tsatsomeros}")
        pass
    else:
        pb += 1
        #         print(f"\n ----- Unclear answer: Is A a P-Matrix ?\noutput_tsatsomeros:{output_tsatsomeros}\noutput_rohn_v1:{output_rohn_v1}\noutput_rohn_v2:{output_rohn_v2}")
        #         print("\nCall tsatsomeros:\n")
        #         output_tsatsomeros = p_matrix_Tsatsomeros(matrix, True)
        #         print(output_tsatsomeros)
        #         print("\nCall rohn v1:\n")
        #         output_rohn_v1, J, msg_rohn_v1 = p_matrix_Rohn_v1(matrix, True)
        #         print(output_rohn_v1, msg_rohn_v1)
        #         print("\nCall rohn v2:\n")
        #         output_rohn_v2, msg_rohn_v2 = p_matrix_Rohn_v2(matrix, True)
        #         print(output_rohn_v2, msg_rohn_v2)
        
print("\n\n\nCHECKING DONE")
print(r"positive def matrix")
print(f"matrix shape {n}x{n}, {nbr_iter} estimations")
print(f"proportion of results where algorithms do not give the same output: {pb / (nbr_iter - cannot_solve )}")




CHECKING DONE
positive def matrix
matrix shape 8x8, 100 estimations
proportion of results where algorithms do not give the same output: 0.0


In [19]:
n = 50
nbr_iter = 50
pb = 0
cannot_solve = 0

for _ in range(nbr_iter):

    normalized_matrix = np.random.normal(loc=0.0, scale=1.0, size=(n,n)).round(3) / sqrt(n)
    matrix = np.eye(n) - normalized_matrix

    output_rohn_v1, J, msg_rohn_v1 = p_matrix_Rohn_v1(matrix, False)
    if output_rohn_v1 == 1:
        output_rohn_v1 = True
    elif output_rohn_v1 == 0:
        output_rohn_v1 = False

    output_rohn_v2, msg_rohn_v2 = p_matrix_Rohn_v2(matrix, False)
    if output_rohn_v2 == 1:
        output_rohn_v2 = True
    elif output_rohn_v2 == 0:
        output_rohn_v2 = False

    if (output_rohn_v1 == -1) | (output_rohn_v2 == -1):
        cannot_solve += 1
    elif output_rohn_v1 == output_rohn_v2:
        #         print(f"\n ----- Clear answer: Is A a P-Matrix ? {output_tsatsomeros}")
        pass
    else:
        pb += 1
        #         print(f"\n ----- Unclear answer: Is A a P-Matrix ?\noutput_rohn_v1:{output_rohn_v1}\noutput_rohn_v2:{output_rohn_v2}")
        #         print("\nCall rohn v1:\n")
        #         output_rohn_v1, J, msg_rohn_v1 = p_matrix_Rohn_v1(matrix, True)
        #         print(output_rohn_v1, msg_rohn_v1)
        #         print("\nCall rohn v2:\n")
        #         output_rohn_v2, msg_rohn_v2 = p_matrix_Rohn_v2(matrix, True)
        #         print(output_rohn_v2, msg_rohn_v2)
        
print("\n\n\nCHECKING DONE")
print(r"non symmetric random matrix")
print(f"matrix shape {n}x{n}, {nbr_iter} estimations")
print(f"proportion of results where algorithms do not give the same output: {pb / (nbr_iter - cannot_solve )}")

0


KeyboardInterrupt: 