**p_matrix_Tsatsomeros** algorithm is based on :

@article{title = {Principal minors, Part I: A method for computing all the principal minors of a matrix},
journal = {Linear Algebra and its Applications},
volume = {419},
number = {1},
pages = {107-124},
year = {2006},
issn = {0024-3795},
doi = {https://doi.org/10.1016/j.laa.2006.04.008},
url = {https://www.sciencedirect.com/science/article/pii/S0024379506002126},
author = {Kent Griffin and Michael J. Tsatsomeros},
keywords = {Principal submatrix, Schur complement, P-matrix, P-problem},
abstract = {An order O(2n) algorithm for computing all the principal minors of an arbitrary n×n complex matrix is motivated and presented, offering an improvement by a factor of n3 over direct computation. The algorithm uses recursive Schur complementation and submatrix extraction, storing the answer in a binary order. An implementation of the algorithm in MATLAB® is also given and practical considerations are discussed and treated accordingly.}}

(see also :
- page 21/22 http://www.math.wsu.edu/faculty/tsat/files/PmatricesLectureNotes.pdf
- page 4 http://www.math.wsu.edu/faculty/tsat/files/tl_c.pdf)

**p_matrix_Rohn** algorithm is based on :
  
@article{title = {An Algorithm for Solving the P-Matrix Problem},
journal = {Národní úložiště šedé literatury},
url = {https://invenio.nusl.cz/record/81055/files/content.csg.pdf},
author = {Jiří Rohn},
keywords = {P-matrix problem}}

motivated by : https://www.sciencedirect.com/science/article/pii/S0024379501005900

(see also :
- https://www.sciencedirect.com/science/article/pii/S0024379511001418
- https://www.researchgate.net/publication/228571326_An_Algorithm_for_Checking_Regularity_of_Interval_Matrices)

In [ ]:
from uutils import *
import numpy as np
from math import *
import sympy
import random

In [2]:
n = 5
A = generate_p_matrix(n)
print(A) # P MATRIX TRUE

pm, J = p_matrix_Rohn(A)

if pm == 1:
    print(True)
else: 
    print(False)
    
print(p_matrix_Tsatsomeros(A))

[[ 1.18303811  0.34743281  0.24611074  0.23896902  0.26072786]
 [-0.13253477  0.63888907 -0.27131472 -0.26577734 -0.22894912]
 [ 0.23957181  0.3761981   1.33739962  0.2809312   0.34163931]
 [ 0.05542568  0.01137236  0.07206297  0.99460319  0.06013833]
 [-0.15283764 -0.48512302 -0.34154688 -0.34017676  0.6598052 ]]
True
True


In [3]:
A = np.array([[1,2],
              [3,-1]])
print(A) # P MATRIX FALSE

pm, J = p_matrix_Rohn(A)

if pm == 1:
    print(True)
else: 
    print(False)
    
print(p_matrix_Tsatsomeros(A))

[[ 1  2]
 [ 3 -1]]
False
False


In [4]:
A = np.array([[1,2],
              [3,1]])
print(A) # P MATRIX FALSE

pm, J = p_matrix_Rohn(A)

if pm == 1:
    print(True)
else: 
    print(False)
    
print(p_matrix_Tsatsomeros(A))

[[1 2]
 [3 1]]
False
False


In [5]:
A = np.array([[1,2,3],
              [3,1,3],
              [2,3,1]])
print(A) # P MATRIX FALSE

pm, J = p_matrix_Rohn(A)

if pm == 1:
    print(True)
else: 
    print(False)
    
print(p_matrix_Tsatsomeros(A))

[[1 2 3]
 [3 1 3]
 [2 3 1]]
False
False


In [6]:
# http://www.math.wsu.edu/faculty/tsat/files/pcon_c.pdf ($3 \times 3$ matrix sign pattern $\iff$ p-matrix)
    
A = np.array([[1,2,5],
              [-3,5,1],
              [0,-20,10]])
print(A) # P MATRIX TRUE (sign pattern from the paper above)

pm, J = p_matrix_Rohn(A)

if pm == 1:
    print(True)
else: 
    print(False)
    
print(p_matrix_Tsatsomeros(A))

[[  1   2   5]
 [ -3   5   1]
 [  0 -20  10]]
True
True
